import type { NicheConfig, NicheId } from './niche.types';

/**
 * Single source of truth for all niche-specific content and branding.
 * Swapping ACTIVE_NICHE (or building a separate entry point that imports
 * a different id) re-skins the entire app with no component changes.
 */
export const ACTIVE_NICHE: NicheId = 'quit-vaping';

const quitVaping: NicheConfig = {
  id: 'quit-vaping',
  appName: 'ClearAir',
  tagline: 'Breathe easy. One day at a time.',
  relapseTerm: 'slip',
  relapseTermPast: 'slipped',
  streakNoun: 'vape-free streak',
  colors: {
    primary: '#3DD9C4',
    primaryDark: '#1FA98F',
    secondary: '#7C9CFF',
    accent: '#FFB37C',
    gradientStart: '#3DD9C4',
    gradientEnd: '#7C9CFF',
  },
  calculator: {
    currencySymbol: '$',
    unitSingular: 'vape',
    unitPlural: 'vapes',
    defaultCostPerUnit: 18,
    defaultUnitsPerDay: 1,
    costPerUnitQuestion: 'About how much does one pod or disposable vape cost you?',
    unitsPerDayQuestion: 'On average, how many pods or disposables do you go through per day?',
    unitsAvoidedLabel: 'Vapes avoided',
    moneySavedLabel: 'Money saved',
  },
  onboardingQuiz: [
    {
      id: 'severity',
      question: 'How often were you vaping?',
      subtitle: 'Be honest — this just helps us tailor your plan.',
      type: 'single',
      options: [
        { id: 'occasional', label: 'A few times a week', icon: '🌤️' },
        { id: 'daily', label: 'Daily', icon: '☁️' },
        { id: 'heavy', label: 'Multiple times a day', icon: '🌧️' },
        { id: 'constant', label: 'Almost constantly', icon: '⛈️' },
      ],
    },
    {
      id: 'triggers',
      question: 'When do you usually reach for a vape?',
      subtitle: 'Select all that apply.',
      type: 'multi',
      options: [
        { id: 'stress', label: 'Stress or anxiety', icon: '😣' },
        { id: 'boredom', label: 'Boredom', icon: '🥱' },
        { id: 'social', label: 'Around others who vape', icon: '👥' },
        { id: 'after_meal', label: 'After meals', icon: '🍽️' },
        { id: 'driving', label: 'Driving', icon: '🚗' },
        { id: 'morning', label: 'First thing in the morning', icon: '🌅' },
      ],
    },
    {
      id: 'past_attempts',
      question: 'Have you tried to quit before?',
      type: 'single',
      options: [
        { id: 'never', label: 'This is my first try', icon: '🌱' },
        { id: 'once', label: 'Once or twice', icon: '🔁' },
        { id: 'many', label: 'Several times', icon: '🔄' },
        { id: 'many_relapsed', label: 'Many times, always relapsed', icon: '💭' },
      ],
    },
  ],
  whyMotivations: [
    { id: 'health', label: 'My health and lungs', icon: '🫁' },
    { id: 'family', label: 'My family', icon: '👨‍👩‍👧' },
    { id: 'money', label: 'Save money', icon: '💰' },
    { id: 'control', label: 'Take back control', icon: '🧠' },
    { id: 'fitness', label: 'Fitness and energy', icon: '🏃' },
    { id: 'future_kids', label: 'A future kid or pregnancy', icon: '👶' },
  ],
  milestones: [
    { id: 'm20min', hours: 0.33, title: '20 Minutes', description: 'Heart rate and blood pressure begin to drop.', icon: '💓' },
    { id: 'm24h', hours: 24, title: '24 Hours', description: 'Nicotine levels drop and anxiety may spike — this is normal.', icon: '🌅' },
    { id: 'm72h', hours: 72, title: '3 Days', description: 'Nicotine is fully out of your body. Withdrawal peaks here.', icon: '💪' },
    { id: 'm1w', hours: 168, title: '1 Week', description: 'Cravings shorten. Taste and smell continue improving.', icon: '🎉' },
    { id: 'm1m', hours: 720, title: '1 Month', description: 'Lung function and circulation are noticeably better.', icon: '🏆' },
    { id: 'm3m', hours: 2160, title: '3 Months', description: 'Coughing and shortness of breath drop significantly.', icon: '🌟' },
    { id: 'm1y', hours: 8760, title: '1 Year', description: 'Risk of major health complications has dropped sharply.', icon: '👑' },
  ],
  recoveryTimeline: [
    { hours: 0.33, title: 'Heart rate normalizes', body: 'Your pulse and blood pressure start returning to normal levels within minutes.' },
    { hours: 8, title: 'Oxygen levels rise', body: 'Blood oxygen levels increase as carbon monoxide (if smoking too) clears out.' },
    { hours: 24, title: 'Nicotine drops sharply', body: 'Most nicotine has left your bloodstream. Cravings and irritability peak soon.' },
    { hours: 72, title: 'Bronchial tubes relax', body: 'Breathing becomes easier as airways relax and energy levels rise.' },
    { hours: 336, title: 'Circulation improves', body: 'Blood circulation improves noticeably, making exercise easier.' },
    { hours: 2160, title: 'Lung cilia regrow', body: 'Tiny hair-like structures in your lungs regrow, reducing infection risk and clearing mucus.' },
    { hours: 8760, title: 'Long-term risk drops', body: 'Risk of heart disease continues to fall the longer you stay vape-free.' },
  ],
  education: [
    { id: 'e1', unlockDay: 0, title: 'Why nicotine hooks you', icon: '🧬', body: 'Nicotine reaches your brain in about 10 seconds, triggering a dopamine release that your brain quickly learns to crave. Understanding this loop is the first step to breaking it — cravings are a chemical signal, not a character flaw, and they reliably fade within minutes if you ride them out.' },
    { id: 'e2', unlockDay: 1, title: 'The 4 D\'s for cravings', icon: '🛡️', body: 'When a craving hits, try Delay (wait 5 minutes), Deep breathe, Drink water, and Do something else with your hands. Most cravings peak and fade within 3-5 minutes. Having a go-to response ready removes the decision-making burden in the moment, which is when willpower is weakest.' },
    { id: 'e3', unlockDay: 2, title: 'Withdrawal is temporary', icon: '⏳', body: 'Irritability, trouble focusing, and restlessness typically peak around day 3 and fade substantially by day 10-14. Your brain is recalibrating its dopamine baseline. Naming the symptom for what it is — a temporary withdrawal wave — makes it easier to ride out without reaching for a vape.' },
    { id: 'e4', unlockDay: 4, title: 'Replacing the ritual', icon: '🔁', body: 'Much of vaping is habit and ritual, not just chemistry — the hand-to-mouth motion, the exhale, the pause it gives you. Identify what the ritual gave you (a break, a fidget, a breath) and swap in something that meets the same need, like stretching, chewing gum, or a short walk.' },
    { id: 'e5', unlockDay: 6, title: 'Handling social pressure', icon: '👥', body: 'Being around others who vape is one of the top relapse triggers. Decide your response ahead of time — a simple "I\'m good, quit vaping" is usually enough. Rehearsing this reduces the split-second hesitation that can turn into a slip.' },
    { id: 'e6', unlockDay: 9, title: 'Lung healing timeline', icon: '🫁', body: 'Within weeks of quitting, cilia — tiny hairs that clear mucus and debris — begin regrowing in your lungs. This reduces coughing and infection risk over time. Breathing exercises and light cardio can help support this recovery.' },
    { id: 'e7', unlockDay: 13, title: 'Planning for a slip', icon: '🧭', body: 'Most people who successfully quit have at least one slip along the way. A slip is data, not a verdict — it tells you which trigger needs a stronger plan. Treat it as information, log it, and get back to your streak the same day.' },
  ],
  distractionActivities: [
    { id: 'd1', title: '10 jumping jacks', durationSeconds: 30, instructions: 'Stand up and do 10 quick jumping jacks. Physical movement burns off restless energy and shifts your focus fast.' },
    { id: 'd2', title: 'Cold water splash', durationSeconds: 20, instructions: 'Splash cold water on your face or hold an ice cube. The cold sensation interrupts the craving signal.' },
    { id: 'd3', title: 'Text someone', durationSeconds: 60, instructions: 'Send a quick message to a friend or family member — just say hi. Connection is a proven craving-buster.' },
    { id: 'd4', title: 'Chew something', durationSeconds: 45, instructions: 'Grab gum, a mint, or a crunchy snack. Give your mouth something else to do for the next minute.' },
  ],
  motivationalCards: [
    { id: 'mc1', text: 'This craving will pass in a few minutes whether you vape or not. You get to choose what happens next.' },
    { id: 'mc2', text: 'Every hour you stay vape-free, your lungs are already healing.' },
    { id: 'mc3', text: 'You didn\'t come this far to only come this far.' },
    { id: 'mc4', text: 'Remember your why. It\'s still there, waiting on the other side of this craving.' },
  ],
  triggerTags: [
    { id: 'stress', label: 'Stress', icon: '😣' },
    { id: 'boredom', label: 'Boredom', icon: '🥱' },
    { id: 'social', label: 'Social situation', icon: '👥' },
    { id: 'alcohol', label: 'Drinking', icon: '🍺' },
    { id: 'habit', label: 'Just habit', icon: '🔁' },
    { id: 'other', label: 'Other', icon: '❓' },
  ],
  emotionTags: [
    { id: 'anxious', label: 'Anxious', icon: '😰' },
    { id: 'sad', label: 'Sad', icon: '😢' },
    { id: 'angry', label: 'Angry', icon: '😠' },
    { id: 'lonely', label: 'Lonely', icon: '😔' },
    { id: 'happy', label: 'Actually happy', icon: '😊' },
    { id: 'numb', label: 'Numb / on autopilot', icon: '😶' },
  ],
  paywall: {
    trialDays: 3,
    annualPrice: 39.99,
    monthlyPrice: 8.99,
    currencySymbol: '$',
    headline: 'Start your vape-free life',
    subheadline: '3 days free, then continue for less than the cost of one pod pack.',
    features: [
      'Personalized quit plan and streak tracking',
      'Unlimited SOS urge relief sessions',
      'Full recovery timeline and education library',
      'Anonymous community support',
    ],
    revenueCatEntitlementId: 'premium',
    revenueCatOfferingId: 'default',
  },
};

const quitPorn: NicheConfig = {
  id: 'quit-porn',
  appName: 'Reframe',
  tagline: 'Rewire your mind. Reclaim your focus.',
  relapseTerm: 'relapse',
  relapseTermPast: 'relapsed',
  streakNoun: 'streak',
  colors: {
    primary: '#6C63FF',
    primaryDark: '#4A3FCF',
    secondary: '#3DD9C4',
    accent: '#FF8FA3',
    gradientStart: '#6C63FF',
    gradientEnd: '#3DD9C4',
  },
  calculator: {
    currencySymbol: '$',
    unitSingular: 'binge',
    unitPlural: 'binges',
    defaultCostPerUnit: 0,
    defaultUnitsPerDay: 1,
    costPerUnitQuestion: 'Roughly how much time (in minutes) did a typical session cost you?',
    unitsPerDayQuestion: 'How many times per week were you typically viewing?',
    unitsAvoidedLabel: 'Sessions avoided',
    moneySavedLabel: 'Hours reclaimed',
  },
  onboardingQuiz: [
    {
      id: 'severity',
      question: 'How often were you viewing?',
      subtitle: 'Be honest — this just helps us tailor your plan.',
      type: 'single',
      options: [
        { id: 'occasional', label: 'A few times a month', icon: '🌤️' },
        { id: 'weekly', label: 'Weekly', icon: '☁️' },
        { id: 'daily', label: 'Daily', icon: '🌧️' },
        { id: 'multiple', label: 'Multiple times a day', icon: '⛈️' },
      ],
    },
    {
      id: 'triggers',
      question: 'What usually leads to a session?',
      subtitle: 'Select all that apply.',
      type: 'multi',
      options: [
        { id: 'stress', label: 'Stress or anxiety', icon: '😣' },
        { id: 'boredom', label: 'Boredom', icon: '🥱' },
        { id: 'loneliness', label: 'Loneliness', icon: '😔' },
        { id: 'late_night', label: 'Late at night', icon: '🌙' },
        { id: 'phone_alone', label: 'Alone with my phone', icon: '📱' },
        { id: 'after_conflict', label: 'After an argument', icon: '💢' },
      ],
    },
    {
      id: 'past_attempts',
      question: 'Have you tried to quit before?',
      type: 'single',
      options: [
        { id: 'never', label: 'This is my first try', icon: '🌱' },
        { id: 'once', label: 'Once or twice', icon: '🔁' },
        { id: 'many', label: 'Several times', icon: '🔄' },
        { id: 'many_relapsed', label: 'Many times, always relapsed', icon: '💭' },
      ],
    },
  ],
  whyMotivations: [
    { id: 'relationship', label: 'My relationship', icon: '💞' },
    { id: 'focus', label: 'Mental clarity and focus', icon: '🧠' },
    { id: 'confidence', label: 'Self-respect and confidence', icon: '🌟' },
    { id: 'values', label: 'Living by my values', icon: '🧭' },
    { id: 'time', label: 'Time back in my day', icon: '⏳' },
    { id: 'faith', label: 'Faith or personal growth', icon: '🙏' },
  ],
  milestones: [
    { id: 'm1h', hours: 1, title: '1 Hour', description: 'You made it through the first hour — the hardest urge often passes fast.', icon: '💓' },
    { id: 'm24h', hours: 24, title: '24 Hours', description: 'Dopamine levels begin to stabilize.', icon: '🌅' },
    { id: 'm3d', hours: 72, title: '3 Days', description: 'Mental fog starts lifting for many people around this point.', icon: '💪' },
    { id: 'm1w', hours: 168, title: '1 Week', description: 'Sleep quality and focus often begin improving.', icon: '🎉' },
    { id: 'm1m', hours: 720, title: '1 Month', description: 'Reward pathways are recalibrating toward natural rewards.', icon: '🏆' },
    { id: 'm3m', hours: 2160, title: '3 Months', description: 'Many report significantly reduced cravings and better mood.', icon: '🌟' },
    { id: 'm1y', hours: 8760, title: '1 Year', description: 'A full year of rewired habits and reclaimed time.', icon: '👑' },
  ],
  recoveryTimeline: [
    { hours: 1, title: 'Urge intensity peaks and fades', body: 'The initial urge is typically the strongest and begins fading within 20-30 minutes if not acted on.' },
    { hours: 24, title: 'Dopamine begins resetting', body: 'Without the artificial spike, your brain\'s reward system starts recalibrating toward everyday pleasures.' },
    { hours: 72, title: 'Mental fog starts lifting', body: 'Many report clearer thinking and better concentration as the acute withdrawal period passes.' },
    { hours: 336, title: 'Sleep improves', body: 'Sleep quality often improves as late-night viewing habits are removed from the routine.' },
    { hours: 720, title: 'Motivation returns', body: 'Natural motivation and drive for goals often rebound as reward sensitivity normalizes.' },
    { hours: 2160, title: 'Reward pathways rewire', body: 'Sustained abstinence allows reward circuitry to recalibrate toward real-world connection and achievement.' },
    { hours: 8760, title: 'New baseline established', body: 'A year of consistency builds a genuinely new default — cravings become rare and manageable.' },
  ],
  education: [
    { id: 'e1', unlockDay: 0, title: 'Understanding the dopamine loop', icon: '🧬', body: 'Viewing triggers a large, fast dopamine spike that your brain learns to chase, dulling response to everyday rewards over time. Recognizing this as a chemical loop — not a moral failing — helps you approach recovery with self-compassion instead of shame.' },
    { id: 'e2', unlockDay: 1, title: 'The urge surfing technique', icon: '🌊', body: 'Instead of fighting an urge, imagine it as a wave: it rises, peaks, and falls whether you act on it or not. Most urges peak within 10-20 minutes. Naming the sensation ("this is an urge, it will pass") helps you ride it out without giving in.' },
    { id: 'e3', unlockDay: 2, title: 'Environment design', icon: '🛡️', body: 'Willpower is limited, but environment is controllable. Use device-level content filters, charge your phone outside the bedroom, and remove private browsing access where possible. Making the unwanted behavior harder to access reduces reliance on in-the-moment willpower.' },
    { id: 'e4', unlockDay: 4, title: 'What triggers really mean', icon: '🔁', body: 'Loneliness, boredom, and stress are the most common triggers. Each one is really an unmet need — for connection, stimulation, or relief. Identifying the underlying need lets you meet it directly instead of through a compulsive substitute.' },
    { id: 'e5', unlockDay: 6, title: 'Rebuilding real connection', icon: '👥', body: 'Isolation both feeds and is fed by compulsive viewing. Rebuilding regular, low-stakes social contact — a call, a shared meal, a group activity — restores a natural source of connection and reduces reliance on the habit.' },
    { id: 'e6', unlockDay: 9, title: 'Sleep and screen habits', icon: '🌙', body: 'Late-night alone time is a high-risk window. A simple phone-charging-outside-the-bedroom rule and a wind-down routine can remove the opportunity for a slip during the most vulnerable hours of the day.' },
    { id: 'e7', unlockDay: 13, title: 'Reframing a relapse', icon: '🧭', body: 'A relapse is common in recovery from any compulsive habit and does not erase your progress. What matters is what you do in the next hour: log it, note the trigger, and return to your plan without spiraling into shame.' },
  ],
  distractionActivities: [
    { id: 'd1', title: '10 pushups', durationSeconds: 30, instructions: 'Drop and do 10 pushups (or a modified version). Physical exertion redirects arousal and energy fast.' },
    { id: 'd2', title: 'Cold water splash', durationSeconds: 20, instructions: 'Splash cold water on your face. The cold sensation interrupts the urge signal quickly.' },
    { id: 'd3', title: 'Call or text someone', durationSeconds: 60, instructions: 'Reach out to a friend, accountability partner, or family member right now — just to talk.' },
    { id: 'd4', title: 'Leave the room', durationSeconds: 30, instructions: 'Physically get up and go to a different room or step outside. Changing location breaks the pattern.' },
  ],
  motivationalCards: [
    { id: 'mc1', text: 'This urge is a wave. It will crest and fall whether you act on it or not.' },
    { id: 'mc2', text: 'You are not your urges. You are what you do next.' },
    { id: 'mc3', text: 'Every hour clean is rewiring your brain toward real rewards.' },
    { id: 'mc4', text: 'Remember your why. It\'s still there, waiting on the other side of this urge.' },
  ],
  triggerTags: [
    { id: 'stress', label: 'Stress', icon: '😣' },
    { id: 'boredom', label: 'Boredom', icon: '🥱' },
    { id: 'loneliness', label: 'Loneliness', icon: '😔' },
    { id: 'late_night', label: 'Late at night', icon: '🌙' },
    { id: 'phone', label: 'Alone with phone', icon: '📱' },
    { id: 'other', label: 'Other', icon: '❓' },
  ],
  emotionTags: [
    { id: 'anxious', label: 'Anxious', icon: '😰' },
    { id: 'sad', label: 'Sad', icon: '😢' },
    { id: 'bored', label: 'Bored', icon: '🥱' },
    { id: 'lonely', label: 'Lonely', icon: '😔' },
    { id: 'ashamed', label: 'Ashamed', icon: '😞' },
    { id: 'numb', label: 'Numb / on autopilot', icon: '😶' },
  ],
  paywall: {
    trialDays: 3,
    annualPrice: 44.99,
    monthlyPrice: 9.99,
    currencySymbol: '$',
    headline: 'Start reclaiming your mind',
    subheadline: '3 days free, then continue for less than a coffee a month.',
    features: [
      'Personalized recovery plan and streak tracking',
      'Unlimited SOS urge relief sessions',
      'Full recovery timeline and education library',
      'Anonymous community support',
    ],
    revenueCatEntitlementId: 'premium',
    revenueCatOfferingId: 'default',
  },
};

const quitSugar: NicheConfig = {
  id: 'quit-sugar',
  appName: 'SweetFree',
  tagline: 'Break the cycle. Feel the difference.',
  relapseTerm: 'slip',
  relapseTermPast: 'slipped',
  streakNoun: 'sugar-free streak',
  colors: {
    primary: '#FF8FA3',
    primaryDark: '#E56B82',
    secondary: '#FFC978',
    accent: '#6C63FF',
    gradientStart: '#FF8FA3',
    gradientEnd: '#FFC978',
  },
  calculator: {
    currencySymbol: '$',
    unitSingular: 'sugary treat',
    unitPlural: 'sugary treats',
    defaultCostPerUnit: 4,
    defaultUnitsPerDay: 2,
    costPerUnitQuestion: 'About how much do you spend on one sugary snack or drink?',
    unitsPerDayQuestion: 'How many sugary snacks or drinks do you typically have per day?',
    unitsAvoidedLabel: 'Treats avoided',
    moneySavedLabel: 'Money saved',
  },
  onboardingQuiz: [
    {
      id: 'severity',
      question: 'How often are you eating added sugar?',
      subtitle: 'Be honest — this just helps us tailor your plan.',
      type: 'single',
      options: [
        { id: 'occasional', label: 'A few times a week', icon: '🌤️' },
        { id: 'daily', label: 'Daily', icon: '☁️' },
        { id: 'heavy', label: 'Multiple times a day', icon: '🌧️' },
        { id: 'constant', label: 'Constantly craving it', icon: '⛈️' },
      ],
    },
    {
      id: 'triggers',
      question: 'When do cravings hit hardest?',
      subtitle: 'Select all that apply.',
      type: 'multi',
      options: [
        { id: 'stress', label: 'Stress', icon: '😣' },
        { id: 'afternoon_slump', label: 'Afternoon energy slump', icon: '😴' },
        { id: 'after_meal', label: 'After meals', icon: '🍽️' },
        { id: 'social', label: 'Social gatherings', icon: '👥' },
        { id: 'boredom', label: 'Boredom', icon: '🥱' },
        { id: 'late_night', label: 'Late night snacking', icon: '🌙' },
      ],
    },
    {
      id: 'past_attempts',
      question: 'Have you tried cutting sugar before?',
      type: 'single',
      options: [
        { id: 'never', label: 'This is my first try', icon: '🌱' },
        { id: 'once', label: 'Once or twice', icon: '🔁' },
        { id: 'many', label: 'Several times', icon: '🔄' },
        { id: 'many_relapsed', label: 'Many times, always went back', icon: '💭' },
      ],
    },
  ],
  whyMotivations: [
    { id: 'health', label: 'My long-term health', icon: '❤️' },
    { id: 'weight', label: 'Reach a healthy weight', icon: '⚖️' },
    { id: 'energy', label: 'Stable energy all day', icon: '⚡' },
    { id: 'skin', label: 'Clearer skin', icon: '✨' },
    { id: 'family', label: 'Be a role model for my family', icon: '👨‍👩‍👧' },
    { id: 'control', label: 'Take back control', icon: '🧠' },
  ],
  milestones: [
    { id: 'm12h', hours: 12, title: '12 Hours', description: 'Blood sugar begins to stabilize.', icon: '💓' },
    { id: 'm24h', hours: 24, title: '24 Hours', description: 'Cravings and irritability may peak — this is temporary.', icon: '🌅' },
    { id: 'm72h', hours: 72, title: '3 Days', description: 'Sugar withdrawal symptoms typically ease up.', icon: '💪' },
    { id: 'm1w', hours: 168, title: '1 Week', description: 'Energy levels start to feel steadier throughout the day.', icon: '🎉' },
    { id: 'm1m', hours: 720, title: '1 Month', description: 'Taste buds reset — food starts tasting naturally sweeter.', icon: '🏆' },
    { id: 'm3m', hours: 2160, title: '3 Months', description: 'Many notice improved skin, sleep, and mood.', icon: '🌟' },
    { id: 'm1y', hours: 8760, title: '1 Year', description: 'A full year of better metabolic health.', icon: '👑' },
  ],
  recoveryTimeline: [
    { hours: 12, title: 'Blood sugar stabilizes', body: 'Insulin spikes from sugar begin to level out, reducing energy crashes.' },
    { hours: 24, title: 'Cravings peak', body: 'This is often the hardest point — sugar withdrawal can mimic other cravings, but it passes.' },
    { hours: 72, title: 'Energy stabilizes', body: 'Many people notice steadier energy without the sugar rollercoaster.' },
    { hours: 336, title: 'Sleep improves', body: 'Reduced blood sugar swings often lead to more restful, consistent sleep.' },
    { hours: 720, title: 'Taste buds reset', body: 'Sensitivity to sweetness increases, making whole foods taste more satisfying.' },
    { hours: 2160, title: 'Skin and mood improve', body: 'Reduced inflammation from added sugar can improve skin clarity and mood stability.' },
    { hours: 8760, title: 'Metabolic health improves', body: 'A full year of lower added-sugar intake supports better long-term metabolic markers.' },
  ],
  education: [
    { id: 'e1', unlockDay: 0, title: 'Why sugar is so addictive', icon: '🧬', body: 'Sugar triggers a dopamine response similar to other addictive substances, and frequent spikes train your brain to crave more. Understanding this chemical loop helps you approach cravings with strategy instead of guilt.' },
    { id: 'e2', unlockDay: 1, title: 'Riding out a craving', icon: '🌊', body: 'Most sugar cravings peak and fade within 10-15 minutes. Drinking water, taking a short walk, or eating a piece of fruit can bridge the gap until the craving passes on its own.' },
    { id: 'e3', unlockDay: 2, title: 'Reading hidden sugar labels', icon: '🔍', body: 'Sugar hides under names like dextrose, maltose, and cane juice on ingredient labels. Learning to spot these helps you make informed choices without needing to rely on willpower alone at the grocery store.' },
    { id: 'e4', unlockDay: 4, title: 'The blood sugar rollercoaster', icon: '🎢', body: 'Sugar spikes are quickly followed by crashes that feel like fatigue or hunger, prompting more sugar intake. Pairing carbs with protein or fiber flattens this curve and reduces the urge to reach for something sweet.' },
    { id: 'e5', unlockDay: 6, title: 'Building a swap list', icon: '🔁', body: 'Keep a short list of go-to swaps — berries, nuts, or dark chocolate — so you have a ready answer when a craving hits, instead of deciding under pressure.' },
    { id: 'e6', unlockDay: 9, title: 'Sleep and sugar cravings', icon: '😴', body: 'Poor sleep increases cravings for sugary, high-calorie foods the next day. Prioritizing consistent sleep is one of the most effective ways to reduce baseline craving intensity.' },
    { id: 'e7', unlockDay: 13, title: 'Reframing a slip', icon: '🧭', body: 'One sugary treat doesn\'t undo your progress. Treat it as information about a trigger, log it, and get back to your plan at the very next meal.' },
  ],
  distractionActivities: [
    { id: 'd1', title: 'Drink a glass of water', durationSeconds: 30, instructions: 'Sugar cravings are sometimes actually thirst. Drink a full glass of water and wait a few minutes.' },
    { id: 'd2', title: 'Short walk', durationSeconds: 60, instructions: 'Step outside or walk around your space for a minute. Movement shifts focus away from the craving.' },
    { id: 'd3', title: 'Eat a piece of fruit', durationSeconds: 45, instructions: 'Satisfy the urge for sweetness with a piece of whole fruit instead.' },
    { id: 'd4', title: 'Brush your teeth', durationSeconds: 45, instructions: 'A clean mouth feeling makes sugary food less appealing in the moment.' },
  ],
  motivationalCards: [
    { id: 'mc1', text: 'This craving will pass in a few minutes whether you eat sugar or not.' },
    { id: 'mc2', text: 'Every hour without added sugar, your energy is already stabilizing.' },
    { id: 'mc3', text: 'You didn\'t come this far to only come this far.' },
    { id: 'mc4', text: 'Remember your why. It\'s still there, waiting on the other side of this craving.' },
  ],
  triggerTags: [
    { id: 'stress', label: 'Stress', icon: '😣' },
    { id: 'afternoon_slump', label: 'Afternoon slump', icon: '😴' },
    { id: 'social', label: 'Social situation', icon: '👥' },
    { id: 'boredom', label: 'Boredom', icon: '🥱' },
    { id: 'habit', label: 'Just habit', icon: '🔁' },
    { id: 'other', label: 'Other', icon: '❓' },
  ],
  emotionTags: [
    { id: 'anxious', label: 'Anxious', icon: '😰' },
    { id: 'sad', label: 'Sad', icon: '😢' },
    { id: 'tired', label: 'Tired', icon: '😴' },
    { id: 'bored', label: 'Bored', icon: '🥱' },
    { id: 'happy', label: 'Actually happy', icon: '😊' },
    { id: 'numb', label: 'Numb / on autopilot', icon: '😶' },
  ],
  paywall: {
    trialDays: 3,
    annualPrice: 34.99,
    monthlyPrice: 7.99,
    currencySymbol: '$',
    headline: 'Start your sugar-free life',
    subheadline: '3 days free, then continue for less than one sugary drink a month.',
    features: [
      'Personalized quit plan and streak tracking',
      'Unlimited SOS craving relief sessions',
      'Full recovery timeline and education library',
      'Anonymous community support',
    ],
    revenueCatEntitlementId: 'premium',
    revenueCatOfferingId: 'default',
  },
};

const quitSmoking: NicheConfig = {
  id: 'quit-smoking',
  appName: 'FreshStart',
  tagline: 'Every cigarette not smoked is a win.',
  relapseTerm: 'slip',
  relapseTermPast: 'slipped',
  streakNoun: 'smoke-free streak',
  colors: {
    primary: '#4A90D9',
    primaryDark: '#2C6CB0',
    secondary: '#3DD9C4',
    accent: '#FFB37C',
    gradientStart: '#4A90D9',
    gradientEnd: '#3DD9C4',
  },
  calculator: {
    currencySymbol: '$',
    unitSingular: 'cigarette',
    unitPlural: 'cigarettes',
    defaultCostPerUnit: 0.45,
    defaultUnitsPerDay: 12,
    costPerUnitQuestion: 'About how much does one cigarette cost you (pack price ÷ cigarettes per pack)?',
    unitsPerDayQuestion: 'On average, how many cigarettes do you smoke per day?',
    unitsAvoidedLabel: 'Cigarettes avoided',
    moneySavedLabel: 'Money saved',
  },
  onboardingQuiz: [
    {
      id: 'severity',
      question: 'How many cigarettes do you smoke per day?',
      subtitle: 'Be honest — this just helps us tailor your plan.',
      type: 'single',
      options: [
        { id: 'light', label: 'Fewer than 5', icon: '🌤️' },
        { id: 'moderate', label: '5 to 15', icon: '☁️' },
        { id: 'heavy', label: '16 to 25', icon: '🌧️' },
        { id: 'very_heavy', label: 'More than 25', icon: '⛈️' },
      ],
    },
    {
      id: 'triggers',
      question: 'When do you usually reach for a cigarette?',
      subtitle: 'Select all that apply.',
      type: 'multi',
      options: [
        { id: 'stress', label: 'Stress', icon: '😣' },
        { id: 'coffee', label: 'With coffee', icon: '☕' },
        { id: 'after_meal', label: 'After meals', icon: '🍽️' },
        { id: 'social', label: 'Around other smokers', icon: '👥' },
        { id: 'driving', label: 'Driving', icon: '🚗' },
        { id: 'break', label: 'Work breaks', icon: '⏱️' },
      ],
    },
    {
      id: 'past_attempts',
      question: 'Have you tried to quit before?',
      type: 'single',
      options: [
        { id: 'never', label: 'This is my first try', icon: '🌱' },
        { id: 'once', label: 'Once or twice', icon: '🔁' },
        { id: 'many', label: 'Several times', icon: '🔄' },
        { id: 'many_relapsed', label: 'Many times, always relapsed', icon: '💭' },
      ],
    },
  ],
  whyMotivations: [
    { id: 'health', label: 'My health', icon: '❤️' },
    { id: 'family', label: 'My family', icon: '👨‍👩‍👧' },
    { id: 'money', label: 'Save money', icon: '💰' },
    { id: 'control', label: 'Take back control', icon: '🧠' },
    { id: 'fitness', label: 'Fitness and energy', icon: '🏃' },
    { id: 'future_kids', label: 'A future kid or pregnancy', icon: '👶' },
  ],
  milestones: [
    { id: 'm20min', hours: 0.33, title: '20 Minutes', description: 'Heart rate drops back toward normal.', icon: '💓' },
    { id: 'm12h', hours: 12, title: '12 Hours', description: 'Carbon monoxide levels in your blood drop to normal.', icon: '🌅' },
    { id: 'm72h', hours: 72, title: '3 Days', description: 'Nicotine is fully out of your body. Breathing feels easier.', icon: '💪' },
    { id: 'm2w', hours: 336, title: '2 Weeks', description: 'Circulation improves and lung function starts increasing.', icon: '🎉' },
    { id: 'm1m', hours: 720, title: '1 Month', description: 'Coughing and shortness of breath decrease noticeably.', icon: '🏆' },
    { id: 'm1y', hours: 8760, title: '1 Year', description: 'Risk of heart disease is about half that of a smoker.', icon: '🌟' },
    { id: 'm5y', hours: 43800, title: '5 Years', description: 'Stroke risk drops to near that of a non-smoker.', icon: '👑' },
  ],
  recoveryTimeline: [
    { hours: 0.33, title: 'Heart rate drops', body: 'Your pulse begins returning to a normal resting rate within 20 minutes.' },
    { hours: 12, title: 'Carbon monoxide clears', body: 'Blood oxygen levels rise back to normal as carbon monoxide clears your system.' },
    { hours: 72, title: 'Nicotine fully leaves', body: 'Breathing may feel easier as bronchial tubes relax and energy increases.' },
    { hours: 336, title: 'Circulation improves', body: 'Walking and light exercise become noticeably easier as circulation improves.' },
    { hours: 720, title: 'Lung function rises', body: 'Coughing decreases as lung function increases by up to 10%.' },
    { hours: 8760, title: 'Heart disease risk halves', body: 'Excess risk of coronary heart disease drops to about half that of a smoker.' },
    { hours: 43800, title: 'Stroke risk normalizes', body: 'Risk of stroke can fall to that of a non-smoker within 5 years.' },
  ],
  education: [
    { id: 'e1', unlockDay: 0, title: 'Why nicotine hooks you', icon: '🧬', body: 'Nicotine reaches your brain within about 10 seconds of a puff, triggering a dopamine release your brain learns to crave. Cravings are a chemical signal, not a character flaw, and they reliably fade within minutes if you ride them out.' },
    { id: 'e2', unlockDay: 1, title: 'The 4 D\'s for cravings', icon: '🛡️', body: 'When a craving hits, try Delay, Deep breathe, Drink water, and Do something else with your hands. Most cravings peak and fade within 3-5 minutes.' },
    { id: 'e3', unlockDay: 2, title: 'Withdrawal is temporary', icon: '⏳', body: 'Irritability and restlessness typically peak around day 3 and fade substantially by day 10-14 as your brain recalibrates its dopamine baseline.' },
    { id: 'e4', unlockDay: 4, title: 'Replacing the ritual', icon: '🔁', body: 'Much of smoking is habit — the hand-to-mouth motion, the break it gives you. Identify what the ritual gave you and swap in something that meets the same need.' },
    { id: 'e5', unlockDay: 6, title: 'Handling social pressure', icon: '👥', body: 'Being around other smokers is a top relapse trigger. Decide your response ahead of time so you don\'t hesitate in the moment.' },
    { id: 'e6', unlockDay: 9, title: 'Lung healing timeline', icon: '🫁', body: 'Within weeks of quitting, cilia begin regrowing in your lungs, reducing coughing and infection risk over time.' },
    { id: 'e7', unlockDay: 13, title: 'Planning for a slip', icon: '🧭', body: 'Most people who successfully quit smoking have at least one slip along the way. Treat it as data, log it, and get back to your streak the same day.' },
  ],
  distractionActivities: [
    { id: 'd1', title: '10 jumping jacks', durationSeconds: 30, instructions: 'Stand up and do 10 quick jumping jacks to burn off restless energy.' },
    { id: 'd2', title: 'Cold water splash', durationSeconds: 20, instructions: 'Splash cold water on your face or hold an ice cube to interrupt the craving.' },
    { id: 'd3', title: 'Text someone', durationSeconds: 60, instructions: 'Send a quick message to a friend or family member — connection is a proven craving-buster.' },
    { id: 'd4', title: 'Chew something', durationSeconds: 45, instructions: 'Grab gum or a crunchy snack to give your mouth something else to do.' },
  ],
  motivationalCards: [
    { id: 'mc1', text: 'This craving will pass in a few minutes whether you smoke or not.' },
    { id: 'mc2', text: 'Every hour smoke-free, your lungs and heart are already healing.' },
    { id: 'mc3', text: 'You didn\'t come this far to only come this far.' },
    { id: 'mc4', text: 'Remember your why. It\'s still there, waiting on the other side of this craving.' },
  ],
  triggerTags: [
    { id: 'stress', label: 'Stress', icon: '😣' },
    { id: 'coffee', label: 'Coffee', icon: '☕' },
    { id: 'social', label: 'Social situation', icon: '👥' },
    { id: 'alcohol', label: 'Drinking', icon: '🍺' },
    { id: 'habit', label: 'Just habit', icon: '🔁' },
    { id: 'other', label: 'Other', icon: '❓' },
  ],
  emotionTags: [
    { id: 'anxious', label: 'Anxious', icon: '😰' },
    { id: 'sad', label: 'Sad', icon: '😢' },
    { id: 'angry', label: 'Angry', icon: '😠' },
    { id: 'bored', label: 'Bored', icon: '🥱' },
    { id: 'happy', label: 'Actually happy', icon: '😊' },
    { id: 'numb', label: 'Numb / on autopilot', icon: '😶' },
  ],
  paywall: {
    trialDays: 3,
    annualPrice: 39.99,
    monthlyPrice: 8.99,
    currencySymbol: '$',
    headline: 'Start your smoke-free life',
    subheadline: '3 days free, then continue for less than the cost of one pack.',
    features: [
      'Personalized quit plan and streak tracking',
      'Unlimited SOS urge relief sessions',
      'Full recovery timeline and education library',
      'Anonymous community support',
    ],
    revenueCatEntitlementId: 'premium',
    revenueCatOfferingId: 'default',
  },
};

export const NICHE_REGISTRY: Record<NicheId, NicheConfig> = {
  'quit-vaping': quitVaping,
  'quit-porn': quitPorn,
  'quit-sugar': quitSugar,
  'quit-smoking': quitSmoking,
};

export const niche: NicheConfig = NICHE_REGISTRY[ACTIVE_NICHE];

export * from './niche.types';
